# Generated by Django 4.1.2 on 2022-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='day_of_week',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='focusarea',
            name='time_of_task',
            field=models.TimeField(),
        ),
    ]
