# Generated by Django 4.1.2 on 2022-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_area', '0002_alter_focusarea_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusarea',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
