# Generated by Django 4.1.2 on 2022-10-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_area', '0004_focusarea_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
