# Generated by Django 4.1.2 on 2022-10-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('focus_area', '0009_rename_backgroundcolor_focusarea_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='color',
            field=models.CharField(default='red', max_length=50),
        ),
    ]
