# Generated by Django 4.1.2 on 2022-10-13 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('focus_area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_of_progress', models.IntegerField()),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='focus_area.focusarea')),
            ],
        ),
    ]
