# Generated by Django 4.1.2 on 2022-10-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_tracker', '0002_progresstracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
